var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/users/[id]/route.js")
R.c("server/chunks/[externals]_node:crypto_950c7d07._.js")
R.c("server/chunks/bd6a9_d24-project-p07-show-your-skills-workspace_src_generated_runtime_client_c1f29eb3.js")
R.c("server/chunks/41795_-your-skills-workspace_src_generated_query_compiler_fast_bg_wasm-base64_c7222173.js")
R.c("server/chunks/bb94c_sd24-project-p07-show-your-skills-workspace_src_generated_023fc0d3._.js")
R.c("server/chunks/56734_ROCMondriaanTIN_sd24-project-p07-show-your-skills-workspace_src_lib_61e61fa0._.js")
R.c("server/chunks/d7eaf_roject-p07-show-your-skills-workspace_app_api_admin_users_[id]_route_ts_c45007bd._.js")
R.c("server/chunks/[externals]__95f01553._.js")
R.c("server/chunks/9dd8c_next_336c4f9b._.js")
R.c("server/chunks/9dd8c_mariadb_d9340b7c._.js")
R.c("server/chunks/d5c6f_iconv-lite_98121eac._.js")
R.c("server/chunks/9dd8c_next-auth_50864355._.js")
R.c("server/chunks/9dd8c_openid-client_e8d145db._.js")
R.c("server/chunks/9dd8c_jose_dist_node_cjs_9bdeecf1._.js")
R.c("server/chunks/[root-of-the-server]__eebe2192._.js")
R.c("server/chunks/dc8a6__next-internal_server_app_api_admin_users_[id]_route_actions_19bececc.js")
R.m("[project]/github-classroom/ROCMondriaanTIN/sd24-project-p07-show-your-skills-workspace/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/github-classroom/ROCMondriaanTIN/sd24-project-p07-show-your-skills-workspace/app/api/admin/users/[id]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/github-classroom/ROCMondriaanTIN/sd24-project-p07-show-your-skills-workspace/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/github-classroom/ROCMondriaanTIN/sd24-project-p07-show-your-skills-workspace/app/api/admin/users/[id]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
