var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/[...nextauth]/route.js")
R.c("server/chunks/[externals]_node:crypto_b871f5bf._.js")
R.c("server/chunks/bd6a9_d24-project-p07-show-your-skills-workspace_src_generated_runtime_client_c1f29eb3.js")
R.c("server/chunks/41795_-your-skills-workspace_src_generated_query_compiler_fast_bg_wasm-base64_c7222173.js")
R.c("server/chunks/bb94c_sd24-project-p07-show-your-skills-workspace_src_generated_023fc0d3._.js")
R.c("server/chunks/bb94c_sd24-project-p07-show-your-skills-workspace_src_lib_prisma_ts_32485ae3._.js")
R.c("server/chunks/cb83d_ject-p07-show-your-skills-workspace_app_api_auth_[___nextauth]_route_ts_2048e1cb._.js")
R.c("server/chunks/[externals]__3391084c._.js")
R.c("server/chunks/9dd8c_next_6d729963._.js")
R.c("server/chunks/9dd8c_next-auth_50864355._.js")
R.c("server/chunks/9dd8c_openid-client_e8d145db._.js")
R.c("server/chunks/9dd8c_jose_dist_node_cjs_9bdeecf1._.js")
R.c("server/chunks/9dd8c_mariadb_d9340b7c._.js")
R.c("server/chunks/d5c6f_iconv-lite_98121eac._.js")
R.c("server/chunks/[root-of-the-server]__37aeacf1._.js")
R.c("server/chunks/dc8a6__next-internal_server_app_api_auth_[___nextauth]_route_actions_93f4b526.js")
R.m("[project]/github-classroom/ROCMondriaanTIN/sd24-project-p07-show-your-skills-workspace/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/github-classroom/ROCMondriaanTIN/sd24-project-p07-show-your-skills-workspace/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/github-classroom/ROCMondriaanTIN/sd24-project-p07-show-your-skills-workspace/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/github-classroom/ROCMondriaanTIN/sd24-project-p07-show-your-skills-workspace/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
